web:
  build: node/
  command: 'bash -c ''npm install; npm start;'''
  working_dir: /app/user
  environment:
    PORT: 3000
  ports:
    - '3000:3000'
shell:
  build: node/
  command: bash
  working_dir: /app/user
  environment:
    PORT: 3000
  ports:
    - '3000:3000'
  volumes:
    - '.:/app/user'
