web:
  container_name: microsb-server
  build: node/
  command: 'bash -c ''npm install; npm start;'''
  working_dir: /app/user
  environment:
    PORT: 3000
    REDIS_URL: 'redis://herokuRedis:6379'
  ports:
    - '3000:3000'
  links:
    - herokuRedis

shell:
  container_name: microsb-shell
  build: node/
  command: bash
  working_dir: /app/user
  environment:
    PORT: 3000
    REDIS_URL: 'redis://herokuRedis:6379'
  ports:
    - '3000:3000'
  volumes:
    - './node:/app/user'
  links:
    - herokuRedis

herokuRedis:
  container_name: microsb-redis
  image: redis
